Repository emeryberger/CSrankings, pull requests merged in 2025-08, with the labels that each got.

#8936 Update Tao Yue 0002 from Beihang University in csrankings-t.csv
  csrankings-t.csv
Labels: validated

#8934 Updating Faculty of McMaster University
  csrankings-c.csv
  csrankings-i.csv
  csrankings-j.csv
  csrankings-l.csv
  csrankings-s.csv
  csrankings-y.csv
Labels: validated

#8944 Adding Muoi Tran from Chalmers/GU
  csrankings-m.csv
Labels: validated

#8945 Add Pulkit agrawal mit to csrankings
  csrankings-p.csv
Labels: validated

#8954 Adding multiple new faculty in the CS department at UT Dallas
  csrankings-a.csv
  csrankings-c.csv
  csrankings-i.csv
  csrankings-j.csv
  csrankings-l.csv
  csrankings-s.csv
Labels: validated

#8960 Updates to UMD CS - Add Asst. Profs Can Firtina and Sarah Wiegreffe
  csrankings-c.csv
  csrankings-s.csv
Labels: validated

#8364 Updated faculty members at Griffith University
  csrankings-a.csv
  csrankings-m.csv
  csrankings-z.csv
Labels: stale, validated

#8990 Carlos Jensen moved to UMBC
  csrankings-c.csv
Labels: stale

#9046 Add Lucie Flek to Uni Bonn csrankings-l.csv
  csrankings-l.csv
Labels: stale

#8910 Add Faculties from IIIS, Tsinghua University.
  csrankings-h.csv
  csrankings-j.csv
  csrankings-k.csv
  csrankings-l.csv
  csrankings-t.csv
  csrankings-y.csv
  csrankings-z.csv
Labels: validated

#8920 Add Zirui Zhuang to BUPT
  csrankings-z.csv
Labels: validated

#8941 Add Zhijiang Guo from HKUST
  csrankings-z.csv
Labels: validated

#8942 update affiliations of three former MSU faculty members
  csrankings-g.csv
  csrankings-j.csv
  csrankings-y.csv
Labels: validated

#8964 Updating McMaster University as of 7 August 2025
  csrankings-a.csv
  csrankings-c.csv
  csrankings-d.csv
  csrankings-g.csv
  csrankings-m.csv
  csrankings-n.csv
  csrankings-r.csv
  csrankings-y.csv
Labels: stale

#8967 Fix Name of Kyung Hee University Professor for DBLP Search
  csrankings-s.csv
Labels: validated

#8971 Add Zhou Yang to University of Alberta
  csrankings-z.csv
Labels: validated

#8973 add Yongqiang Tian from Monash University
  csrankings-y.csv
Labels: validated

#8981 adding a new HKBU Comp faculty member: Long-Kai Huang
  csrankings-l.csv
Labels: validated

#8983 U. Colorado Boulder: update Huck Bennett, add Ramin Ayanzadeh
  csrankings-h.csv
  csrankings-r.csv
Labels: validated

#8984 Adding Wenya Wang to csrankings-w.csv
  csrankings-w.csv
Labels: validated

#8987 Update csrankings-z.csv Add Ziqi Xu to CSRankings
  csrankings-z.csv
Labels: validated

#8989 Add Zhipeng Gao from Zhejiang University
  csrankings-z.csv
Labels: validated

#8992 Add Yuxia Zhang and Hui Liu from Beijing Institute of Technology
  csrankings-h.csv
  csrankings-y.csv
Labels: validated

#8993 Add Gautam Shroff, Nikhil Gupta, Ravi Anand, Supratim Shit and Tanmoy Kundu as faculty of IIIT Delhi
  csrankings-g.csv
  csrankings-n.csv
  csrankings-r.csv
  csrankings-s.csv
  csrankings-t.csv
Labels: validated

#8998 Add Haoye Tian to Aalto University
  csrankings-h.csv
Labels: validated

#9005 Fix homepage link for Prof. Yiyu Shi at University of Notre Dame
  csrankings-y.csv
Labels: validated

#9024 Rochester Institute of Technology: add Lingwei Chen and Chongzhou Fang
  csrankings-c.csv
  csrankings-l.csv
Labels: validated

#9029 Add Zan Wang, Yingquan Zhao to Tianjin University
  csrankings-y.csv
  csrankings-z.csv
Labels: validated

#9033 Add multiple new CS faculty at UCF
  csrankings-a.csv
  csrankings-g.csv
  csrankings-k.csv
  csrankings-r.csv
  csrankings-s.csv
Labels: validated

#9036 Add new WSU faculty (Abhishek Moitra)
  csrankings-a.csv
Labels: validated

#9081 update three IUB CS faculty affiliations
  csrankings-l.csv
  csrankings-x.csv
  csrankings-y.csv
Labels: validated

#9078 Add Jiaqi Wang, a new faculty of Auburn University CS department.
  csrankings-j.csv
Labels: validated

#9063 Add Shengwei An to Virginia Tech
  csrankings-s.csv
Labels: validated

#9041 update cs faculty at UC
  csrankings-t.csv
Labels: validated

#8985 Update Texas A&M University
  csrankings-s.csv
  csrankings-z.csv
Labels: stale, validated
