Repository emeryberger/CSrankings, pull requests merged in 2025-09, with the labels that each got.

#9084 Add Juho Leinonen to Aalto University
  csrankings-j.csv
Labels: validated

#9083 add two missing UMN faculties
  csrankings-c.csv
  csrankings-j.csv
Labels: validated

#9082 Update Xiaofeng Wang & Jiyuan Wang's affiliations: Xiaofeng Wang is n…
  csrankings-j.csv
  csrankings-x.csv
Labels: validated

#9011 add 15 people from a department of the University of Twente
  csrankings-a.csv
  csrankings-e.csv
  csrankings-f.csv
  csrankings-g.csv
  csrankings-m.csv
  csrankings-p.csv
  csrankings-t.csv
  csrankings-v.csv
  csrankings-y.csv
Labels: validated

#9085 Updated home page(s) for UMass faculty
  csrankings-b.csv
  csrankings-h.csv
  csrankings-m.csv
  csrankings-p.csv
  csrankings-r.csv
  csrankings-s.csv
  csrankings-y.csv
Labels: validated

#9073 Added Ali Siahkoohi, Jialin Liu, Pegah Khosravi, Shashank Sonkar, Song Wang, Wu Lin, and Xinyu Chen to University of Central Florida. Updated Christian Kuemmerle's institution to University of Central Florida
  csrankings-a.csv
  csrankings-c.csv
  csrankings-j.csv
  csrankings-p.csv
  csrankings-s.csv
  csrankings-w.csv
  csrankings-x.csv
Labels: validated

#9010 add Chunwei Liu from Purdue faculty to CSRanking
  csrankings-c.csv
Labels: validated

#8994 Add Wenzheng Chen from Peking University to csrankings-w.csv
  csrankings-w.csv
Labels: stale, validated

#9089 Added faculty members of Shahid Beheshti University
  csrankings-d.csv
  csrankings-m.csv
  csrankings-y.csv
Labels: validated

#9098 Add more PR validation checks
  .github/workflows/commit_validation.yml
  generate_diff.py
  validate_commit.py
Labels: validated

#9096 Adding a new faculty in CSE PSU in security area
  csrankings-a.csv
Labels: validated

#9102 UNIST faculty: add new entry (updated csrankings-r.csv)
  csrankings-r.csv
Labels: validated

#9113 Add new CS faculty of VinUniversity
  csrankings-h.csv
  csrankings-m.csv
  csrankings-s.csv
  csrankings-t.csv
  csrankings-v.csv
  csrankings-z.csv
Labels: stale

#9122 U Victoria faculty changes
  csrankings-a.csv
  csrankings-b.csv
  csrankings-f.csv
  csrankings-s.csv
  csrankings-v.csv
  csrankings-w.csv
  csrankings-z.csv
Labels: validated

#9125 Delete former U Vic Faculty
  csrankings-s.csv
Labels: validated
